<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="api-test" tests="1" time="0.000">
  <testsuite name="get merchant" id="c852b74b-1ed2-4549-998f-631a1dff4113" timestamp="2024-05-09T09:08:29.786Z" tests="1" failures="1" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

---
]]></system-err>
    <testcase name="Status code is 200" time="0.000" classname="ApiTest">
      <failure type="AssertionFailure" message="expected PostmanResponse{ …(5) } to have property 'code'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 6802a33b-6260-4cd7-b604-7f7ce62a3d9b.]]>
        <![CDATA[Collection name: api-test.]]>
        <![CDATA[Request name: get merchant.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected PostmanResponse{ …(5) } to have property 'code'.]]>
        <![CDATA[Stacktrace: AssertionError: expected PostmanResponse{ …(5) } to have property 'code'
   at Object.eval sandbox-script.js:1:1).]]>
      </failure>
    </testcase>
  </testsuite>
</testsuites>